# This file is used to configure GitHub Sponsors for this repository
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: yashvyas95
# ko_fi: yashvyas95
# custom: ["https://buymeacoffee.com/yashvyas95"]
