# Stale issue/PR configuration
# https://github.com/actions/stale

daysBeforeStale: 60
daysBeforeClose: 14
exemptLabels:
  - pinned
  - security
  - good first issue
  - help wanted
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed in 14 days if no further activity occurs.
  Thank you for your contributions!
closeComment: >
  This issue was automatically closed because it has been stale for 14 days
  with no activity. Feel free to reopen if this is still relevant.
